#!/usr/bin/env bash
# Install Nginx in my remote server

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
