#!/usr/bin/env bash
# displays to infinty and beyond and sleep 2 and I am invincible !!!
# when recieving a SIGTERM SIGNAL
while [ True ]
do
	echo "To infinity and beyond"
	sleep 2
	echo "I am invincible!!!"
done
