#!/usr/bin/env bash
# displays to infinty and beyond and sleep 2 and I am invincible !!!
# when recieving a SIGTERM SIGNAL
handle_sigterm() {
	echo "I am invincible!!!"
}
trap 'handle_sigterm' SIGTERM
while  true
do
	echo "To infinity and beyond"
	sleep 2
done
