#!/usr/bin/env bash
#this script displays Best School 10 times but displays hi on the 9th iteration
PRINT="Best School"
COUNTER=1
while [ $COUNTER -le 10 ]
do
    echo "$PRINT"
    if [ "$COUNTER" -eq 9 ]
    then
        echo "hi"
    fi
    COUNTER=$(( COUNTER + 1 ))
done
