#!/usr/bin/env bash
#this script displays Best School 10 times but displays bad luck.
#on the 4th iteration and good luck at the 8th iteration.
#Best School for the other iterations.
PRINT="Best School"
COUNTER=1
while [ $COUNTER -le 10 ]
do
    if [ "$COUNTER" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$COUNTER" -eq 8 ]
    then
	echo "good luck"
    else
	echo "$PRINT"
    fi

    COUNTER=$(( COUNTER + 1 ))
done
