#!/usr/bin/env bash
# nginx should be running as the user n listens on port 8080
sed -i 's/user www-data;/user nginx;/' "/etc/nginx/nginx.conf"
sed -i 's/\s*listen\s*80/    listen 8080/' "/etc/nginx/sites-enabled/default"
sudo service nginx restart
