#!/usr/bin/env bash
# nginx should be running as the user n listens on port 8080 as well
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
su nginx -s /bin/bash -c 'service nginx restart'
